services:
  app:
    build:
      context: .
      target: dev
    environment:
      DB_TYPE: mysql
      DB_HOST: mysql
      DB_USERNAME: app
      DB_PASSWORD: password
      DB_NAME: app
      DB_PORT: "3306"
      DB_MIGRATIONS_RUN: "true"
      DB_SYNC: "false"
    volumes:
      - .:/home/node/app
    ports:
      - 9000:3000
    links:
      - mysql
    restart: on-failure

  # Third-party services
  mysql:
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: app
    ports:
      - 4000:3306
